export const HTTP_INTERFACE_METADATA = Symbol("HTTP_INTERFACE_METADATA");
export const HTTP_EXCHANGE_METADATA = Symbol("HTTP_EXCHANGE_METADATA");
export const PATH_VARIABLE_METADATA = Symbol("PATH_VARIABLE_METADATA");
