export const HTTP_INTERFACE_METADATA = Symbol("HTTP_INTERFACE_METADATA");
export const HTTP_EXCHANGE_METADATA = Symbol("HTTP_EXCHANGE_METADATA");
export const PATH_VARIABLE_METADATA = Symbol("PATH_VARIABLE_METADATA");
export const REQUEST_PARAM_METADATA = Symbol("REQUEST_PARAM_METADATA");
export const REQUEST_BODY_METADATA = Symbol("REQUEST_BODY_METADATA");
export const REQUEST_FORM_METADATA = Symbol("REQUEST_BODY_METADATA");
export const REQUEST_HEADER_METADATA = Symbol("REQUEST_HEADER_METADATA");
